# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


source 'https://github.com/CocoaPods/Specs.git'
target 'iNoco' do
	pod 'GroupSettingsManager'
    pod 'google-cast-sdk'
    pod 'Fabric'
    pod 'Crashlytics'
end

#target 'iNocoTests' do
#	pod 'GroupSettingsManager'
#end

target 'iNocoToday' do
	pod 'GroupSettingsManager'
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'iNocoTV' do
    pod 'GroupSettingsManager'
end

